# Generated by Django 2.2.1 on 2019-05-14 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TreeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(max_length=250, unique=True)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Trees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('status', models.CharField(choices=[('SLR', 'Seller'), ('NRML', 'Normal'), ('ADMIN', 'Admin')], default='NRML', max_length=5)),
                ('tree_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.TreeType')),
            ],
        ),
        migrations.CreateModel(
            name='TreeAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=32)),
                ('zip', models.IntegerField()),
                ('trees_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Trees')),
            ],
        ),
    ]
