# Generated by Django 2.2.1 on 2019-05-14 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TreeAddress',
        ),
    ]
