# Generated by Django 2.2.1 on 2019-05-14 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190514_0308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treeaddress',
            name='zip',
        ),
        migrations.AddField(
            model_name='treeaddress',
            name='state',
            field=models.CharField(default=98031, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treeaddress',
            name='zip_code',
            field=models.IntegerField(default=98031),
        ),
    ]
