# Generated by Django 2.2.1 on 2019-05-14 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190514_0547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='in_cart_id',
        ),
        migrations.AlterField(
            model_name='incart',
            name='cart_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trees',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('PENDING', 'Sold'), ('SOLD', 'Pending')], default='AVAILABLE', max_length=5),
        ),
    ]
