# Generated by Django 2.2.1 on 2019-05-14 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_permissions_user_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissions',
            name='perm_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('User', 'User'), ('Seller', 'Seller')], default='User', max_length=9),
        ),
        migrations.AlterField(
            model_name='trees',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('PENDING', 'Sold'), ('SOLD', 'Pending')], default='AVAILABLE', max_length=9),
        ),
    ]
