# Generated by Django 2.2.1 on 2019-05-14 23:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0009_auto_20190514_2107'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_posts',
            new_name='UserPosts',
        ),
    ]
