# Generated by Django 2.2 on 2019-06-05 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190514_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='trees',
            name='location',
            field=models.CharField(default='USA', max_length=250),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TreeAddress',
        ),
    ]
